remote_theme: chrisbobbe/jekyll-theme-prologue
baseurl: "/code-challenge"
url: ""

title: Rembold's Coding Challenges
description: A set of fun little challenges to reinforce proficiency in Python and explore the fun side of coding

avatar: assets/images/avatar.png

collections: [sections]
